version: '3'

services:
  db:
    image: mariadb:10.5.6
    restart: unless-stopped
    container_name: finances-app-db
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
       - ./.db-data:/var/lib/mysql
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    container_name: radd-db-adminer
    ports:
      - 8181:8080
