version: '3'

services:
  db:
    image: mysql:8.0.21
    restart: unless-stopped
    container_name: finances-app-db
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
    - 3306:3306
