on:
  pull_request:
    branches:
      - main

jobs:
  client-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.5.0'
      - name: Run Tests
        run: |
          cd client
          yarn install
          yarn test

  server-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.5.0'
      - name: Run Tests
        run: |
          cd server
          yarn install
          yarn test
